version: '3'

services:

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=topsecret
      - MYSQL_DATABASE=devdb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  package:
    build: .
    volumes:
      - mvn-repo:/root/.m2
      - .:/code
    command: bash -c "mvn clean install && cp /code/target/*.jar /code/app/"

  app:
    build: app/
    depends_on:
      - package
    links:
      - package:package
    command: bash -c "while ping -c1 package &>/dev/null; do sleep 1; done; echo package_finish && java -jar $$(ls *.jar)"
    ports:
      - "8080:8080"

volumes:
  mvn-repo:
    external: true
  mysql-data:
    external: true
