version: '3'

services:

  package:
    build: .
    volumes:
      - mvn-repo:/root/.m2
      - .:/code
    command: bash -c "mvn package && cp /code/target/*.jar /code/app/"

  app:
    build: app/
    depends_on:
      - package
    links:
      - package:package
    command: bash -c "while ping -c1 package &>/dev/null; do sleep 1; done; echo package_finish && java -jar myproject-0.0.1-SNAPSHOT.jar"
    ports:
      - "8080:8080"

volumes:
  mvn-repo:
    external: true
