version: '3'

services:

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=topsecret
      - MYSQL_DATABASE=devdb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: .
    command: bash -c "java -jar $$(ls *.jar)"
    ports:
      - "8080:8080"

volumes:
  mysql-data:
    external: true
