version: '3'

services:
  app:
    build: .
    volumes:
      - mvn-repo:/root/.m2
      - .:/code
    command: mvn spring-boot:run
    ports:
      - "8080:8080"

volumes:
  mvn-repo:
    external: true
